import Head from 'next/head'
import Topbar from '@components/topBar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Vou | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Topbar/>
        oi
      </div>
    </>
  )
}
